### PR TITLE
Implement Redis-style lists for stack and queue functionality

### LINKED ISSUE #14: New ✨ Implement Lists as a DataType for Bluedis
## Issue Description

Lists are a frequently used data structure inside of Redis which allows for the implementation of stacks and queues. The queues are especially useful for implementing Redis Message Queues. The issue proposes an implementation of the same. 

Here's a reference for lists : [Lists in Redis](https://redis.io/docs/latest/develop/data-types/lists/)

## High Level Goals
- [ ] Push data from left or right
- [ ] Pop data from left or right
- [ ] Return length of list
- [ ] Blocking pop from the head of the list
- [ ] Extract range of elements from the list

> [!NOTE]
> As this is a systems programming project, issue are not assigned on a first-come-first-serve basis but rather based on the best approach shared by the contributors for implementing the mentioned feature. Please share your approach below!

### PR DESCRIPTION
**Pull request by FLASH2332**
This file contains the implementation of a Doubly Linked List data structure in Go, which provides the foundational operations needed to implement stacks and queues. The list is designed to support concurrent access, making it suitable for use in a multi-threaded environment, such as a Redis-like message queue system.Solves #14 

### DoublyLinkedList Structure:
The `DoublyLinkedList` struct represents the entire list and contains:

- **head**: A pointer to the first node in the list.  
- **tail**: A pointer to the last node in the list.  
- **length**: An integer representing the number of nodes in the list.  
- **mu**: A mutex for synchronizing access to the list in concurrent environments.  
- **cond**: A condition variable used for blocking operations.  

---

### Core Methods:
1. **PushRight(value interface{})**:  
   Adds a new node with the specified value to the end (tail) of the list.  
   - This method is used to enqueue messages in a queue.

2. **PushLeft(value interface{})**:  
   Adds a new node with the specified value to the beginning (head) of the list.  
   - This method can be used to implement stack behavior or to enqueue messages at the front.

3. **PopLeft()**:  
   Removes and returns the value from the head of the list.  
   - This method is used to dequeue messages from the front of the queue.

4. **PopRight()**:  
   Removes and returns the value from the tail of the list.  
   - This method can be used to implement stack behavior by popping from the end.

5. **BlockingPopLeft()**:  
   A blocking version of `PopLeft()`, which waits until an item is available if the list is empty.  
   - This is useful for implementing message queues where consumers wait for messages.

6. **ExtractRange(start, end int) []interface{}**:  
   Returns a slice of values from the list within the specified range.  
   - This method allows for extracting multiple elements at once, supporting operations like bulk retrieval of messages.

7. **Length() int**:  
   Returns the current number of elements in the list.

---

### Concurrency Support:
- The implementation uses a **mutex (`mu`)** to ensure that operations on the list are thread-safe.  
- This allows multiple producers and consumers to interact with the list concurrently without causing data corruption.

### CODE REVIEW

**Comment by IAmRiteshKoushik** [comment]
@FLASH2332 your code looks good so far. Will carry out an in-depth review later. From a high level I have found certain things missing. 

In order to utilize the functions, we need to expose them via different commands which will be emitted in from the Redis-CLI. 

- [x] LPUSH (push to head)
- [x] LPOP (pop from head)
- [x] RPUSH (push to tail)
- [x] RPOP (pop from tail)
- [x] LLEN (length of list)
- [x] LRANGE (slice of values between 2 indices)
- [x] BLPOP (blocking pop from head)

Additionally, all insertions, updated and deletes must be tracked in an append-only-log which has been implemented in `aof.go`

Please read through the Redis Serialization Protocol (RESP) and figure out the implementation for the same. Also test out the features you have built using Redis-CLI as the client that connects to Bluedis. 

> [!NOTE]
> In case you find the implementation of these to be too challenging and would be happy to receive ONLY 40% of the total bounty for the issue, I am happy to do that as well.

**Comment by FLASH2332** [comment]
I was able to understand the requirements and will work on it

**Comment by FLASH2332** [comment]
> @FLASH2332 your code looks good so far. Will carry out an in-depth review later. From a high level I have found certain things missing.
> 
> In order to utilize the functions, we need to expose them via different commands which will be emitted in from the Redis-CLI.
> 
> * [ ]  LPUSH (push to head)
> * [ ]  LPOP (pop from head)
> * [ ]  RPUSH (push to tail)
> * [ ]  RPOP (pop from tail)
> * [ ]  LLEN (length of list)
> * [ ]  LRANGE (slice of values between 2 indices)
> * [ ]  BLPOP (blocking pop from head)
> 
> Additionally, all insertions, updated and deletes must be tracked in an append-only-log which has been implemented in `aof.go`
> 
> Please read through the Redis Serialization Protocol (RESP) and figure out the implementation for the same. Also test out the features you have built using Redis-CLI as the client that connects to Bluedis.
> 
> Note
> 
> In case you find the implementation of these to be too challenging and would be happy to receive ONLY 40% of the total bounty for the issue, I am happy to do that as well.

 I've implemented the required functions for the Redis commands (LPUSH, LPOP, RPUSH, RPOP, LLEN, LRANGE, and BLPOP) and exposed them through the Redis-CLI. I've also ensured that all insertions, updates, and deletions are tracked in the append-only log (aof.go).

I’ve gone through the Redis Serialization Protocol (RESP) and incorporated the necessary changes accordingly. Additionally, I’ve tested the features using Redis-CLI as the client to connect to Bluedis.

Let me know if there are any further improvements needed.

**Pull request merged**
